version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: favourite_assets
    volumes:
      - db-data:/var/lib/postgresql/data
      - C:/Users/arhsxro/Desktop/VSCode/Go Projects/platform-go-challenge/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_NAME: favourite_assets
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  db-data: